services:
  online-privacy-website:
    image: caddy:latest
    restart: unless-stopped
    # ports:
    #   - 8080:80
    networks:
      - caddy_network
    labels:
      caddy: online-privacy.bastipnt.de
      caddy.reverse_proxy: "{{upstreams}}"
      caddy.header: /*
      caddy.header.Strict-Transport-Security: '"max-age=15552000;"'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/srv
      - online_privacy_data:/data
      - online_privacy_config:/config

volumes:
  online_privacy_data:
  online_privacy_config:

networks:
  caddy_network:
    external: true
